version: '3.8'

services:
  db:
    container_name: db
    image: mariadb:10.5.15
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: silverstripe
      MARIADB_DATABASE: silverstripe
      MARIADB_USER: silverstripe
      MARIADB_PASSWORD: silverstripe
    ports:
      - "3333:3306"

  web:
    container_name: web
    image: brettt89/silverstripe-web:8.1-apache
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    environment:
      DOCUMENT_ROOT: /var/www/html/public
      SS_DATABASE_CLASS: MySQLDatabase
      SS_DATABASE_SERVER: db
      SS_DATABASE_USERNAME: silverstripe
      SS_DATABASE_PASSWORD: silverstripe
      SS_DATABASE_NAME: silverstripe
      SS_ENVIRONMENT_TYPE: dev
      SS_DEFAULT_ADMIN_USERNAME: admin
      SS_DEFAULT_ADMIN_PASSWORD: admin

  frontend:
    image: node:18.4-alpine
    command: /bin/sh -c "npm install && npm run start"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  composer:
    image: composer
    command: composer install --ignore-platform-reqs --no-interaction
    volumes:
      - .:/app

volumes:
  db_data: { }
